---

- name: Make sure Perl is installed
  yum:
    name: perl
    state: present
  when: ansible_os_family == 'RedHat'

- name: Make sure Perl is installed
  apt:
    name: perl
    state: present
  when: ansible_os_family == 'Ubuntu'

- name: Get content of the Grub config file for RedHat <= 6
  shell: cat "{{ grub_cmdline_config_v1 }}" | perl -ane '/(?=.*{{ grub_cmdline_add_args | join(")(?=.*") }})/ && print "YES"'
  register: grub_content
  changed_when: grub_content.stdout | length == 0
  when: >
    ansible_os_family == "RedHat" and
    ansible_distribution_major_version | int <= 6

- name: Update Grub default config for RedHat <= 6
  shell: grubby --args="{{ item }}" --update-kernel=ALL
  with_items: "{{ grub_cmdline_add_args }}"
  when: >
    ansible_os_family == "RedHat" and
    ansible_distribution_major_version | int <= 6 and
    grub_cmdline_add_args | length > 0 and
    grub_content.stdout | length == 0

- name: Remove arguments from Grub default config for RedHat <= 6
  shell: grubby --remove-args="{{ item }}" --update-kernel=ALL
  with_items: "{{ grub_cmdline_remove_args }}"
  when: >
    ansible_os_family == "RedHat" and
    ansible_distribution_major_version | int <= 6 and
    grub_cmdline_remove_args | length > 0

- name: Update Grub default config for RedHat >= 7
  lineinfile:
    dest: "{{ grub_cmdline_default }}"
    line: GRUB_CMDLINE_LINUX="{{ grub_cmdline_add_args | join(' ') }}"
    regexp: '^GRUB_CMDLINE_LINUX="'
  when: >
    ansible_os_family == "RedHat" and
    ansible_distribution_major_version | int >= 7
  notify:
    - Update Grub2 config file

- name: Update Grub default config for Debian
  lineinfile:
    dest: "{{ grub_cmdline_default }}"
    line: GRUB_CMDLINE_LINUX="{{ grub_cmdline_add_args | join(' ') }}"
    regexp: '^GRUB_CMDLINE_LINUX="'
  when: >
    ansible_os_family == "Debian"
  notify:
    - Update Grub2 config file ubuntu

- name: restrict Grub access to admin only Ubuntu
  template:
    src: 42_custom.j2
    dest: /etc/grub.d/42_custom
    owner: root
    group: root
    mode: 0750
  when: >
    ansible_os_family == "Debian"
  notify:
    - Update Grub2 config file ubuntu

- name: allow users to boot Ubuntu
  lineinfile:
    regexp: ^CLASS="--class gnu-linux --class gnu --class os"
    line: CLASS="--class gnu-linux --class gnu --class os --unrestricted"
    dest: /etc/grub.d/10_linux
  when: >
    ansible_os_family == "Debian"
  notify:
    - Update Grub2 config file ubuntu

- name: set default boot to Ubuntu
  lineinfile:
    regexp: ^GRUB_DEFAULT=0
    line: GRUB_DEFAULT="Ubuntu"
    dest: /etc/default/grub
  when: >
    ansible_os_family == "Debian"
  notify:
    - Update Grub2 config file ubuntu

